// Copyright 2016 Openprovider Authors. All rights reserved.
// Use of this source code is governed by a license
// that can be found in the LICENSE file.

package providers

// List of all supported currencies
const (
	AED = "AED"
	AFN = "AFN"
	ALL = "ALL"
	AMD = "AMD"
	ANG = "ANG"
	AOA = "AOA"
	ARS = "ARS"
	AUD = "AUD" // Australian Dollar (A$)
	AWG = "AWG"
	AZN = "AZN"
	BAM = "BAM"
	BBD = "BBD"
	BDT = "BDT"
	BGN = "BGN" // Bulgarian Lev (BGN)
	BHD = "BHD"
	BIF = "BIF"
	BMD = "BMD"
	BND = "BND"
	BOB = "BOB"
	BRL = "BRL" // Brazilian Real (R$)
	BSD = "BSD"
	BTC = "BTC"
	BTN = "BTN"
	BWP = "BWP"
	BYR = "BYR"
	BZD = "BZD"
	CAD = "CAD" // Canadian Dollar (CA$)
	CDF = "CDF"
	CHF = "CHF" // Swiss Franc (CHF)
	CLF = "CLF"
	CLP = "CLP"
	CNY = "CNY" // Chinese Yuan (CN¥)
	COP = "COP"
	CRC = "CRC"
	CUP = "CUP"
	CVE = "CVE"
	CZK = "CZK" // Czech Republic Koruna (CZK)
	DJF = "DJF"
	DKK = "DKK" // Danish Krone (DKK)
	DOP = "DOP"
	DZD = "DZD"
	EEK = "EEK"
	EGP = "EGP"
	ERN = "ERN"
	ETB = "ETB"
	EUR = "EUR" // Euro (€)
	FJD = "FJD"
	FKP = "FKP"
	GBP = "GBP" // British Pound Sterling (£)
	GEL = "GEL"
	GGP = "GGP"
	GHS = "GHS" // Ghanaian cedi (GHS)
	GIP = "GIP"
	GMD = "GMD"
	GNF = "GNF"
	GTQ = "GTQ"
	GYD = "GYD"
	HKD = "HKD" // Hong Kong Dollar (HK$)
	HNL = "HNL"
	HRK = "HRK" // Croatian Kuna (HRK)
	HTG = "HTG"
	HUF = "HUF" // Hungarian Forint (HUF)
	IDR = "IDR" // Indonesian Rupiah (IDR)
	ILS = "ILS" // Israeli New Sheqel (₪)
	IMP = "IMP"
	INR = "INR" // Indian Rupee (Rs.)
	IQD = "IQD"
	IRR = "IRR"
	ISK = "ISK"
	JEP = "JEP"
	JMD = "JMD"
	JOD = "JOD"
	JPY = "JPY" // Japanese Yen (¥)
	KES = "KES"
	KGS = "KGS"
	KHR = "KHR"
	KMF = "KMF"
	KPW = "KPW"
	KRW = "KRW" // South Korean Won (₩)
	KWD = "KWD"
	KYD = "KYD"
	KZT = "KZT"
	LAK = "LAK"
	LBP = "LBP"
	LKR = "LKR" // Sri Lankan Rupee (LKR)
	LRD = "LRD"
	LSL = "LSL"
	LTL = "LTL"
	LVL = "LVL"
	LYD = "LYD"
	MAD = "MAD"
	MDL = "MDL"
	MGA = "MGA"
	MKD = "MKD"
	MMK = "MMK"
	MNT = "MNT"
	MOP = "MOP"
	MRO = "MRO"
	MUR = "MUR"
	MVR = "MVR"
	MWK = "MWK"
	MXN = "MXN" // Mexican Peso (MX$)
	MYR = "MYR" // Malaysian Ringgit (MYR)
	MZN = "MZN"
	NAD = "NAD"
	NGN = "NGN"
	NIO = "NIO"
	NOK = "NOK" // Norwegian Krone (NOK)
	NPR = "NPR"
	NZD = "NZD" // New Zealand Dollar (NZ$)
	OMR = "OMR"
	PAB = "PAB"
	PEN = "PEN"
	PGK = "PGK"
	PHP = "PHP" // Philippine Peso (Php)
	PKR = "PKR"
	PLN = "PLN" // Polish Zloty (PLN)
	PYG = "PYG"
	QAR = "QAR"
	RON = "RON" // Romanian Leu (RON)
	RSD = "RSD"
	RUB = "RUB" // Russian Ruble (RUB)
	RWF = "RWF"
	SAR = "SAR"
	SBD = "SBD"
	SCR = "SCR"
	SDG = "SDG"
	SEK = "SEK" // Swedish Krona (SEK)
	SGD = "SGD" // Singapore Dollar (SGD)
	SHP = "SHP"
	SLL = "SLL"
	SOS = "SOS"
	SRD = "SRD"
	STD = "STD"
	SVC = "SVC"
	SYP = "SYP"
	SZL = "SZL"
	THB = "THB" // Thai Baht (฿)
	TJS = "TJS"
	TMT = "TMT"
	TND = "TND"
	TOP = "TOP"
	TRY = "TRY" // Turkish Lira (TRY)
	TTD = "TTD"
	TWD = "TWD"
	TZS = "TZS"
	UAH = "UAH"
	UGX = "UGX"
	USD = "USD" // US Dollar ($)
	UYU = "UYU"
	UZS = "UZS"
	VEF = "VEF"
	VND = "VND"
	VUV = "VUV"
	WST = "WST"
	XAF = "XAF"
	XAG = "XAG"
	XAU = "XAU"
	XCD = "XCD"
	XDR = "XDR"
	XOF = "XOF"
	XPF = "XPF"
	YER = "YER"
	ZAR = "ZAR" // South African Rand (ZAR)
	ZMK = "ZMK"
	ZMW = "ZMW"
	ZWL = "ZWL"

	// Standard Date/Time template for exchange rates
	stdDateTime = "2006-01-02 15:04:05"
	// Standard Date template for exchange rates
	stdDate = "2006-01-02"
)
